import type { User, District, School, Teacher, Student, GradeConfig, Class } from "./types"

// Mock Districts
export const mockDistricts: District[] = [
  {
    id: "dist-1",
    name: "Metro School District",
    adminId: "admin-1",
    adminName: "Michael Chen",
    adminEmail: "michael.chen@metroschools.edu",
    schoolCount: 12,
    studentCount: 8500,
    createdAt: new Date("2024-01-15"),
    status: "active",
  },
  {
    id: "dist-2",
    name: "Riverside Education District",
    adminId: "admin-2",
    adminName: "Sarah Williams",
    adminEmail: "sarah.williams@riverside.edu",
    schoolCount: 8,
    studentCount: 5200,
    createdAt: new Date("2024-02-20"),
    status: "active",
  },
  {
    id: "dist-3",
    name: "Central Valley Schools",
    adminId: "admin-3",
    adminName: "David Rodriguez",
    adminEmail: "david.rodriguez@centralvalley.edu",
    schoolCount: 15,
    studentCount: 11000,
    createdAt: new Date("2024-01-10"),
    status: "suspended",
  },
]

// Mock District Admins
export const mockDistrictAdmins: User[] = [
  {
    id: "admin-1",
    email: "michael.chen@metroschools.edu",
    displayName: "Michael Chen",
    phoneNumber: "+1-555-0101",
    role: "district-admin",
    status: "active",
    districtId: "dist-1",
    districtName: "Metro School District",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "admin-2",
    email: "sarah.williams@riverside.edu",
    displayName: "Sarah Williams",
    phoneNumber: "+1-555-0102",
    role: "district-admin",
    status: "active",
    districtId: "dist-2",
    districtName: "Riverside Education District",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "admin-3",
    email: "david.rodriguez@centralvalley.edu",
    displayName: "David Rodriguez",
    phoneNumber: "+1-555-0103",
    role: "district-admin",
    status: "suspended",
    districtId: "dist-3",
    districtName: "Central Valley Schools",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-03-15"),
  },
]

// Mock Schools
export const mockSchools: School[] = [
  {
    id: "school-1",
    name: "Lincoln Elementary",
    address: "123 Oak Street",
    zipCode: "10001",
    districtId: "dist-1",
    districtName: "Metro School District",
    adminId: "school-admin-1",
    adminName: "Dr. Maria Rodriguez",
    adminEmail: "maria.rodriguez@lincoln.edu",
    teacherCount: 25,
    studentCount: 450,
    grades: [
      { id: "k", name: "Kindergarten", divisions: ["A", "B"] },
      { id: "1", name: "Grade 1", divisions: ["A", "B", "C"] },
      { id: "2", name: "Grade 2", divisions: ["A", "B"] },
    ],
    createdAt: new Date("2024-01-20"),
    status: "active",
  },
  {
    id: "school-2",
    name: "Washington Middle School",
    address: "456 Pine Avenue",
    zipCode: "10002",
    districtId: "dist-1",
    districtName: "Metro School District",
    adminId: "school-admin-2",
    adminName: "James Thompson",
    adminEmail: "james.thompson@washington.edu",
    teacherCount: 35,
    studentCount: 680,
    grades: [
      { id: "6", name: "Grade 6", divisions: ["A", "B", "C"] },
      { id: "7", name: "Grade 7", divisions: ["A", "B", "C"] },
      { id: "8", name: "Grade 8", divisions: ["A", "B"] },
    ],
    createdAt: new Date("2024-01-25"),
    status: "active",
  },
]

// Mock School Admins
export const mockSchoolAdmins: User[] = [
  {
    id: "school-admin-1",
    email: "maria.rodriguez@lincoln.edu",
    displayName: "Dr. Maria Rodriguez",
    phoneNumber: "+1-555-0201",
    role: "school-admin",
    status: "active",
    districtId: "dist-1",
    districtName: "Metro School District",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    schoolAddress: "123 Oak Street",
    schoolZipCode: "10001",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "school-admin-2",
    email: "james.thompson@washington.edu",
    displayName: "James Thompson",
    phoneNumber: "+1-555-0202",
    role: "school-admin",
    status: "active",
    districtId: "dist-1",
    districtName: "Metro School District",
    schoolId: "school-2",
    schoolName: "Washington Middle School",
    schoolAddress: "456 Pine Avenue",
    schoolZipCode: "10002",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
]

// Mock Teachers
export const mockTeachers: Teacher[] = [
  {
    id: "teacher-1",
    email: "sarah.johnson@lincoln.edu",
    displayName: "Ms. Sarah Johnson",
    phoneNumber: "+1-555-0301",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "1",
    gradeName: "Grade 1",
    division: "A",
    studentCount: 28,
    status: "active",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "teacher-2",
    email: "robert.davis@lincoln.edu",
    displayName: "Mr. Robert Davis",
    phoneNumber: "+1-555-0302",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "1",
    gradeName: "Grade 1",
    division: "B",
    studentCount: 26,
    status: "active",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "teacher-3",
    email: "emily.wilson@lincoln.edu",
    displayName: "Mrs. Emily Wilson",
    phoneNumber: "+1-555-0303",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "2",
    gradeName: "Grade 2",
    division: "A",
    studentCount: 30,
    status: "suspended",
    createdAt: new Date("2024-02-05"),
  },
]

// Mock Students
export const mockStudents: Student[] = [
  {
    id: "student-1",
    email: "emma.thompson@student.edu",
    displayName: "Emma Thompson",
    teacherId: "teacher-1",
    teacherName: "Ms. Sarah Johnson",
    gradeId: "1",
    gradeName: "Grade 1",
    division: "A",
    journalEntries: 45,
    lastActivity: new Date("2024-03-15"),
    status: "active",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "student-2",
    email: "liam.rodriguez@student.edu",
    displayName: "Liam Rodriguez",
    teacherId: "teacher-1",
    teacherName: "Ms. Sarah Johnson",
    gradeId: "1",
    gradeName: "Grade 1",
    division: "A",
    journalEntries: 32,
    lastActivity: new Date("2024-03-14"),
    status: "active",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "student-3",
    email: "sophia.chen@student.edu",
    displayName: "Sophia Chen",
    teacherId: "teacher-1",
    teacherName: "Ms. Sarah Johnson",
    gradeId: "1",
    gradeName: "Grade 1",
    division: "A",
    journalEntries: 52,
    lastActivity: new Date("2024-03-15"),
    status: "active",
    createdAt: new Date("2024-02-12"),
  },
]

// Mock Grade Configurations
export const mockGradeConfigs: GradeConfig[] = [
  {
    id: "grade-k",
    name: "Kindergarten",
    level: 0,
    divisions: [
      { id: "div-k-a", name: "A", maxStudents: 25 },
      { id: "div-k-b", name: "B", maxStudents: 25 },
    ],
    schoolId: "school-1",
    isActive: true,
  },
  {
    id: "grade-1",
    name: "Grade 1",
    level: 1,
    divisions: [
      { id: "div-1-a", name: "A", maxStudents: 28 },
      { id: "div-1-b", name: "B", maxStudents: 28 },
      { id: "div-1-c", name: "C", maxStudents: 28 },
    ],
    schoolId: "school-1",
    isActive: true,
  },
  {
    id: "grade-2",
    name: "Grade 2",
    level: 2,
    divisions: [
      { id: "div-2-a", name: "A", maxStudents: 30 },
      { id: "div-2-b", name: "B", maxStudents: 30 },
    ],
    schoolId: "school-1",
    isActive: true,
  },
]

// Mock Classes
export const mockClasses: Class[] = [
  {
    id: "class-k-a",
    gradeId: "grade-k",
    gradeName: "Kindergarten",
    division: "A",
    schoolId: "school-1",
    teacherId: "teacher-k-a",
    teacherName: "Ms. Emily Davis",
    studentCount: 22,
    maxStudents: 25,
    status: "active",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "class-k-b",
    gradeId: "grade-k",
    gradeName: "Kindergarten",
    division: "B",
    schoolId: "school-1",
    teacherId: "teacher-k-b",
    teacherName: "Mr. Robert Wilson",
    studentCount: 24,
    maxStudents: 25,
    status: "active",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "class-1-a",
    gradeId: "grade-1",
    gradeName: "Grade 1",
    division: "A",
    schoolId: "school-1",
    teacherId: "teacher-1",
    teacherName: "Ms. Sarah Johnson",
    studentCount: 28,
    maxStudents: 28,
    status: "active",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "class-1-b",
    gradeId: "grade-1",
    gradeName: "Grade 1",
    division: "B",
    schoolId: "school-1",
    teacherId: "teacher-2",
    teacherName: "Mr. Robert Davis",
    studentCount: 26,
    maxStudents: 28,
    status: "active",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "class-1-c",
    gradeId: "grade-1",
    gradeName: "Grade 1",
    division: "C",
    schoolId: "school-1",
    studentCount: 0,
    maxStudents: 28,
    status: "active",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "class-2-a",
    gradeId: "grade-2",
    gradeName: "Grade 2",
    division: "A",
    schoolId: "school-1",
    teacherId: "teacher-3",
    teacherName: "Mrs. Emily Wilson",
    studentCount: 30,
    maxStudents: 30,
    status: "active",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "class-2-b",
    gradeId: "grade-2",
    gradeName: "Grade 2",
    division: "B",
    schoolId: "school-1",
    studentCount: 0,
    maxStudents: 30,
    status: "active",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
]

// Update mock teachers with more realistic data
export const mockTeachersUpdated: Teacher[] = [
  {
    id: "teacher-1",
    email: "sarah.johnson@lincoln.edu",
    displayName: "Ms. Sarah Johnson",
    phoneNumber: "+1-555-0301",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "grade-1",
    gradeName: "Grade 1",
    division: "A",
    studentCount: 28,
    status: "active",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "teacher-2",
    email: "robert.davis@lincoln.edu",
    displayName: "Mr. Robert Davis",
    phoneNumber: "+1-555-0302",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "grade-1",
    gradeName: "Grade 1",
    division: "B",
    studentCount: 26,
    status: "active",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "teacher-3",
    email: "emily.wilson@lincoln.edu",
    displayName: "Mrs. Emily Wilson",
    phoneNumber: "+1-555-0303",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "grade-2",
    gradeName: "Grade 2",
    division: "A",
    studentCount: 30,
    status: "active",
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "teacher-k-a",
    email: "emily.davis@lincoln.edu",
    displayName: "Ms. Emily Davis",
    phoneNumber: "+1-555-0304",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "grade-k",
    gradeName: "Kindergarten",
    division: "A",
    studentCount: 22,
    status: "active",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "teacher-k-b",
    email: "robert.wilson@lincoln.edu",
    displayName: "Mr. Robert Wilson",
    phoneNumber: "+1-555-0305",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "grade-k",
    gradeName: "Kindergarten",
    division: "B",
    studentCount: 24,
    status: "active",
    createdAt: new Date("2024-02-01"),
  },
  // Unassigned teachers
  {
    id: "teacher-unassigned-1",
    email: "michael.brown@lincoln.edu",
    displayName: "Mr. Michael Brown",
    phoneNumber: "+1-555-0306",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "",
    gradeName: "",
    division: "",
    studentCount: 0,
    status: "active",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "teacher-unassigned-2",
    email: "lisa.garcia@lincoln.edu",
    displayName: "Ms. Lisa Garcia",
    phoneNumber: "+1-555-0307",
    schoolId: "school-1",
    schoolName: "Lincoln Elementary",
    gradeId: "",
    gradeName: "",
    division: "",
    studentCount: 0,
    status: "active",
    createdAt: new Date("2024-02-12"),
  },
]
